<?php
/**
 * @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
 * DO NOT EDIT THIS FILE! --- use conf/settings.php instead
 * @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
 */

/**
 * URI - PATH MAPPING
 */
$tolc_conf['project_dir'] = $_SERVER['DOCUMENT_ROOT'] . '/path/to/tolc';
$tolc_conf['project_url'] = '/relative_url/to/tolc';

/**
 * DATABASE (or SCHEMA) PER DOMAIN (or SERVER NAME or IP)
 */
$tolc_conf['domains_db'] = array(
	'www.domain.tld' => 'tolc',
	'localhost' => 'tolc'
);

/**
 * DEFAULT TEMPLATE ID PER DOMAIN (or SERVER NAME or IP)
 */
$tolc_conf['domains_tmpl'] = array(
	'www.domain.tld' => 1,
	'localhost' => 1
);

/**
 * DATABASE CONNECTION STRING
 * (http://phplens.com/lens/adodb/docs-adodb.htm#drivers)
 */
$tolc_conf['dbdriver'] = 'mysqli'; // mysqli, mysqlt, mysql, postgres, firebird
$tolc_conf['dbserver'] = 'SERVER-NAME-OR-IP-HERE';
$tolc_conf['dbuser'] = 'USER-HERE';
$tolc_conf['dbpass'] = 'PASSWORD-HERE';
$tolc_conf['dsn_options'] = '?persist=0&fetchmode=2';
$tolc_conf['dsn_custom'] = ''; // sqlite, oci8 (oracle), access, ado_mssql

/**
 * GLOBAL PREFERENCES
 */
/* valid origins */
$tolc_conf['pref_valid_origins'] = array(
	'www.domain.tld',
	'localhost');

/* error reporting (http://php.net/manual/en/function.error-reporting.php) */
$tolc_conf['pref_error_reporting'] = 'E_ALL ^ E_NOTICE';

/* locale */
$tolc_conf['pref_default_locale_code'] = 'en_GB';
$tolc_conf['pref_default_locale_encoding'] = '.UTF-8';

/* URL max length */
$tolc_conf['pref_url_max_length'] = 50;

/* reserved urls */
$tolc_conf['pref_reserved_urls'] = array(
	'login' => '/login',
	'regional' => '/regional'
);

/* this will substitute template active elements default content (if it has value) */
$tolc_conf['pref_tpl_content_subst'] = 'insert content here';

/* tidy settings (http://tidy.sourceforge.net/docs/quickref.html) */
$tolc_conf['pref_use_tidy'] = true;
$tolc_conf['pref_tidy_config'] = array(
	'indent' => TRUE,
	'output-xhtml' => TRUE,
	'wrap' => 200);
$tolc_conf['pref_tidy_encoding'] = 'UTF8';

/* visitor regional settings (default values) */
$tolc_conf['pref_timezone'] = 'UTC';
$tolc_conf['pref_date_format'] = 'd/m/Y'; // http://php.net/manual/en/datetime.formats.date.php
$tolc_conf['pref_decimal_mark'] = '.';
$tolc_conf['pref_thousands_separator'] = ',';

/* user profile */
$tolc_conf['pref_username_minchars'] = 4;
$tolc_conf['pref_username_maxchars'] = 20; // max 254
$tolc_conf['pref_password_minchars'] = 6;
$tolc_conf['pref_password_maxchars'] = 14; // max 254
$tolc_conf['pref_suggested_password_length'] = 12;
$tolc_conf['pref_password_strength'] = 60;
// use of non english characters or other special characters have not tested (NOT RECOMMENDED)
$tolc_conf['pref_password_charset'] = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#_+^~";
$tolc_conf['pref_username_charset'] = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_-.";
$tolc_conf['pref_reserved_usernames'] = array(
	0 => 'admin',
	1 => 'administrator',
	2 => 'postmaster',
	3 => 'sysadmin',
	4 => 'webadmin',
	5 => 'tolc',
	6 => 'tolcadmin'
);

/* jquery ui CSS theme */
$tolc_conf['pref_jqueryui_theme'] = 'ui-lightness'; // ui-lightness, smoothness, south-street, humanity, redmond

/**
 * Using of prepared statements can prevent SQL injection attacks (even if user input is thoroughly sanitized).
 * But, MySQL php extension dows not support prepared statements (only PDO and mysqli).
 * So, this settings is for testing purposes and for future use of PostgreSQL or other RDBMS
 *
 * http://stackoverflow.com/questions/4319162/how-do-i-check-for-emulated-prepared-statements-in-adodb
 * http://stackoverflow.com/questions/2140218/prepared-statement-with-php-and-mysql-without-using-mysqli
 */
$tolc_conf['pref_use_prepared_statements'] = false;
?>